Two species initially excluded for missing coordinates, *C.dolichophylla* and *C.ambodirianensis* are synonyms of distinct accessions of *C.millotii*

Since no coordinates existed and *C. millotii* was already included, no changes are required to the source data

In [12]:
import pandas as pd

# Load the dataset
file_path = r"..\..\..\workdir\input\0026013-240906103802322.csv"
df = pd.read_csv(file_path, sep='\t', engine='python')

df_mg = df[df['countryCode'] == 'MG']

In [18]:
pd.set_option('display.max_colwidth', None)
pd.set_option('display.width', 1000)
pd.set_option('display.expand_frame_repr', False)  # Disable line-wrapping
pd.set_option('display.max_rows', None)

In [13]:
# Define ex situ clues
ex_situ_keywords = ['botanic', 'garden', 'cultivated', 'nursery', 'ex situ', 'greenhouse', 'collection']
ex_situ_institutions = ['RBGK', 'MO', 'PBG', 'BR', 'TEF', 'TAN'] 

# Build masks

mask_locality = df_mg['locality'].astype(str).str.contains('|'.join(ex_situ_keywords), case=False, na=False)
mask_institution = df_mg['institutionCode'].astype(str).isin(ex_situ_institutions)
mask_basisOfRecord = df_mg['basisOfRecord'].astype(str).isin(['LIVING_SPECIMEN'])  # optional stricter filter

# Combine masks: remove records where any mask is True
mask_ex_situ = mask_locality | mask_institution | mask_basisOfRecord

# Filter
df_filtered = df_mg[~mask_ex_situ]

# Save to new file
output_path = r'..\data\0026013-240906103802322_filtered.csv'
df_filtered.to_csv(output_path, index=False)

# Summary
print(f"Original records: {len(df)}")
print(f"MG records: {len(df_mg)}")
print(f"Filtered records: {len(df_filtered)}")
print(f"Filtered data saved to: {output_path}")

Original records: 33668
MG records: 3654
Filtered records: 2332
Filtered data saved to: ..\data\0026013-240906103802322_filtered.csv

In [20]:
counts_df = (
    df_mg
    .groupby('species')   # ou le nom exact de ta colonne espèce
    .size()               # compte le nombre de lignes par groupe
    .reset_index(name='count')
    .sort_values(by='count', ascending=False)
)

counts_df

                    species  count
44      Coffea mangoroensis    156
61          Coffea resinosa    145
28            Coffea grevei    127
62         Coffea richardii    123
55          Coffea perrieri    120
49          Coffea millotii    111
19     Coffea commersoniana    109
69    Coffea tricalysioides    101
23          Coffea dubardii    100
31         Coffea humbertii     96
14        Coffea boiviniana     84
70        Coffea tsirananae     81
51         Coffea mogenetii     75
56       Coffea pervilleana     74
29            Coffea heimii     64
16         Coffea buxifolia     63
20         Coffea coursiana     62
65         Coffea sakarahae     55
39            Coffea leroyi     53
66       Coffea sambavensis     52
40           Coffea liaudii     51
5       Coffea ankaranensis     49
60     Coffea ratsimamangae     47
15          Coffea bonnieri     46
30          Coffea homollei     41
0          Coffea abbayesii     39
12         Coffea bissetiae     38
53           Coffea moratii     37
35    Coffea kianjavatensis     36
3        Coffea ambongensis     34
67         Coffea tetragona     30
13         Coffea boinensis     30
10        Coffea bertrandii     30
59     Coffea rakotonasoloi     29
47       Coffea mcphersonii     29
7         Coffea arenesiana     28
37        Coffea lancifolia     28
52      Coffea montis-sacri     25
2        Coffea ambanjensis     24
25   Coffea farafanganensis     22
71     Coffea vatovavyensis     22
27         Coffea gallienii     20
73          Coffea vianneyi     20
8        Coffea augagneurii     19
33          Coffea jumellei     17
50       Coffea minutiflora     17
64     Coffea sahafaryensis     17
32       Coffea humblotiana     17
58         Coffea pustulata     16
45       Coffea manombensis     16
4   Coffea andrambovatensis     15
74      Coffea vohemarensis     15
42        Coffea littoralis     15
22         Coffea decaryana     14
68            Coffea toshii     13
57        Coffea pterocarpa     12
48     Coffea microdubardii     11
6            Coffea arabica      9
18         Coffea canephora      9
11     Coffea betamponensis      9
36           Coffea labatii      9
72    Coffea vavateninensis      8
63          Coffea rupicola      7
17       Coffea callmanderi      7
41          Coffea liberica      6
54      Coffea namorokensis      6
46        Coffea mauritiana      5
34    Coffea kalobinonensis      4
1        Coffea alleizettii      4
21       Coffea darainensis      3
9       Coffea benghalensis      2
24       Coffea eugenioides      2
26          Coffea fragilis      2
38           Coffea laurina      1
43      Coffea magnistipula      1

In [30]:
counts = df_mg['species'].value_counts()
total_from_counts = counts.sum()

counts_df = (
    df_mg
    .groupby('species')
    .size()
    .reset_index(name='count')
)
total_from_counts_df = counts_df['count'].sum()

# In either case, compare to the number of rows:
n_rows = len(df_mg)

print(f"Sum of counts (value_counts): {total_from_counts}")
print(f"Sum of counts (groupby):      {total_from_counts_df}")
print(f"Number of rows in df_mg:      {n_rows}")

Sum of counts (value_counts): 2914
Sum of counts (groupby):      2914
Number of rows in df_mg:      3654

In [31]:
n_missing = df_mg['species'].isna().sum()

# 2. Nombre de chaînes vides ou espaces seulement
n_empty_str = df_mg['species'].fillna('').astype(str).str.strip().eq('').sum()

print(f"NaN in 'species' column:            {n_missing}")
print(f"Empty strings ('' or spaces only): {n_empty_str}")
print(f"Total rows in df_mg:               {len(df_mg)}")

NaN in 'species' column:            740
Empty strings ('' or spaces only): 740
Total rows in df_mg:               3654

In [26]:
file_path = r"..\data\dr_guyot_all_for_collection.csv"
df2 = pd.read_csv(file_path, engine='python')

In [27]:
counts_df = (
    df2
    .groupby('specimen_id')   # ou le nom exact de ta colonne espèce
    .size()               # compte le nombre de lignes par groupe
    .reset_index(name='count')
    .sort_values(by='count', ascending=False)
)

counts_df

                   specimen_id  count
21            Coffea_canephora    455
69               Coffea_mannii    426
85         Coffea_mufindiensis    177
73          Coffea_mayombensis    171
60             Coffea_liberica    155
32         Coffea_ebracteolata    137
72           Coffea_mauritiana    101
93   Coffea_pseudozanguebariae    100
17             Coffea_brevipes     95
56           Coffea_lebruniana     81
99             Coffea_resinosa     71
68         Coffea_mangoroensis     66
46              Coffea_humilis     66
33          Coffea_eugenioides     65
110        Coffea_sessiliflora     64
82        Coffea_montekupensis     51
81            Coffea_mongensis     49
16              Coffea_brassii     49
96             Coffea_racemosa     46
39               Coffea_grevei     46
14           Coffea_boiviniana     43
90             Coffea_perrieri     43
101           Coffea_richardii     42
28          Coffea_dactylifera     42
31             Coffea_dubardii     41
116          Coffea_tsirananae     39
78             Coffea_millotii     38
44            Coffea_humbertii     37
67         Coffea_magnistipula     37
25            Coffea_congensis     36
122        Coffea_zanguebariae     35
115      Coffea_tricalysioides     35
91          Coffea_pervilleana     31
24        Coffea_commersoniana     31
71              Coffea_mapiana     30
100         Coffea_rhamnifolia     28
113           Coffea_togoensis     28
19            Coffea_buxifolia     28
12            Coffea_bissetiae     23
40               Coffea_heimii     23
80            Coffea_mogenetii     22
34              Coffea_fadenii     21
111         Coffea_stenophylla     19
59              Coffea_liaudii     19
104           Coffea_sakarahae     18
92               Coffea_pocsii     16
112           Coffea_tetragona     15
84              Coffea_moratii     15
64         Coffea_lulandoensis     15
106         Coffea_sambavensis     15
57         Coffea_leonimontana     15
27            Coffea_coursiana     15
0             Coffea_abbayesii     15
9          Coffea_benghalensis     15
15             Coffea_bonnieri     15
109              Coffea_semsei     15
2           Coffea_ambongensis     14
45          Coffea_humblotiana     14
58               Coffea_leroyi     14
108         Coffea_schliebenii     14
13            Coffea_boinensis     13
37             Coffea_fotsoana     13
4          Coffea_ankaranensis     11
5              Coffea_anthonyi     11
51         Coffea_kihansiensis     10
98        Coffea_ratsimamangae     10
74          Coffea_mcphersonii     10
26        Coffea_costatifructa      9
10           Coffea_bertrandii      9
42             Coffea_homollei      9
52          Coffea_kimbozensis      8
95            Coffea_pustulata      8
121           Coffea_wightiana      7
76           Coffea_merguensis      7
6            Coffea_arenesiana      7
120        Coffea_vohemarensis      6
114              Coffea_toshii      6
105           Coffea_salvatrix      6
97        Coffea_rakotonasoloi      6
1           Coffea_ambanjensis      6
8              Coffea_bakossii      6
94           Coffea_pterocarpa      6
49             Coffea_kapakata      5
54              Coffea_labatii      5
18           Coffea_bridsoniae      5
35      Coffea_farafanganensis      5
30            Coffea_decaryana      5
89          Coffea_nkolbisonii      5
47             Coffea_jumellei      4
41          Coffea_heterocalyx      4
50       Coffea_kianjavatensis      4
107             Coffea_sapinii      4
75          Coffea_melanocarpa      4
77        Coffea_microdubardii      4
83         Coffea_montis-sacri      4
86           Coffea_myrtifolia      4
119            Coffea_vianneyi      3
61         Coffea_ligustroides      3
103       Coffea_sahafaryensis      3
22            Coffea_carrissoi      3
55           Coffea_lancifolia      3
11        Coffea_betamponensis      3
3      Coffea_andrambovatensis      3
53            Coffea_kivuensis      3
62           Coffea_littoralis      3
88            Coffea_neoleroyi      3
38            Coffea_gallienii      2
70          Coffea_manombensis      2
117       Coffea_vatovavyensis      2
87         Coffea_namorokensis      2
79          Coffea_minutiflora      2
29          Coffea_darainensis      2
7           Coffea_augagneurii      2
20          Coffea_callmanderi      2
23         Coffea_charrieriana      1
43        Coffea_horsfieldiana      1
48       Coffea_kalobinonensis      1
36           Coffea_floresiana      1
65              Coffea_mabesae      1
63          Coffea_luconiensis      1
66           Coffea_macrocarpa      1
102            Coffea_rupicola      1
118      Coffea_vavateninensis      1