In [13]:
import sklearn
import numpy as np
import scipy as sp
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import re

In [14]:
#coffee_clim_data = pd.read_csv(r"..\data\coll_caff_node_clim.csv")
#coffee_env_data = pd.read_csv(r"..\data\coll_caff_node_env.csv")
coffee_data = pd.read_csv(r"..\data\coll_caff_node_new_jan.csv")

caffeine_content = pd.read_csv(r"..\data\no_caffeine_nodes_w_specimen.csv")

coffee_data.head

<bound method NDFrame.head of      Unnamed: 0     specimen_id  source_crs  longitude   latitude  \
0             0     humbertii_4        4326  43.797500 -22.875000
1             1   richardii_256        4326  50.041667 -14.101389
2             2    perrieri_261        4326  46.333889 -24.560833
3             3    perrieri_262        4326  46.333889 -24.560833
4             4    perrieri_263        4326  46.333889 -24.560833
..          ...             ...         ...        ...        ...
521         521   resinosa_2807        4326  47.000000 -23.000000
522         522   resinosa_2809        4326  48.700000 -13.580000
523         523   dubardii_2812        4326  49.700000 -13.180000
524         524   dubardii_2813        4326  49.700000 -13.180000
525         525  humbertii_2814        4326  44.580000 -22.920000

                                  mada_geom_point  sampled_layers  \
0     POINT (376646.4194813568 7469814.360957881)              79
1    POINT (1044838.0523195444 8435209.185751595)              79
2     POINT (635084.8917711123 7283025.482374048)              79
3     POINT (635084.8917711123 7283025.482374048)              79
4     POINT (635084.8917711123 7283025.482374048)              79
..                                            ...             ...
521   POINT (704992.1724866081 7455081.895663038)              79
522   POINT (900530.2787016315 8495683.113346167)              79
523  POINT (1009820.5473967544 8538182.939559158)              79
524  POINT (1009820.5473967544 8538182.939559158)              79
525   POINT (456932.1646449176 7465274.693208166)              79

     nodata_layers  is_categorical_encoded  \
0                0                    True
1                0                    True
2                0                    True
3                0                    True
4                0                    True
..             ...                     ...
521              0                    True
522              0                    True
523              0                    True
524              0                    True
525              0                    True

     clim_1_tmin1_Monthly minimum temperature - January (°C x 10)  ...  \
0                                                199.0             ...
1                                                217.5             ...
2                                                203.0             ...
3                                                203.0             ...
4                                                203.0             ...
..                                                 ...             ...
521                                              192.5             ...
522                                              225.0             ...
523                                              225.0             ...
524                                              225.0             ...
525                                              192.5             ...

     env_78_wat_Watersheds_RetDisp_Mahavavy  \
0                                         0
1                                         0
2                                         0
3                                         0
4                                         0
..                                      ...
521                                       0
522                                       0
523                                       0
524                                       0
525                                       0

     env_78_wat_Watersheds_RetDisp_Manampatrana  \
0                                             0
1                                             0
2                                             0
3                                             0
4                                             0
..                                          ...
521                                           0
522                                           0
523                                           0
524                                           0
525                                           0

     env_78_wat_Watersheds_RetDisp_Mananara_du_Sud  \
0                                                0
1                                                0
2                                                0
3                                                0
4                                                0
..                                             ...
521                                              1
522                                              0
523                                              0
524                                              0
525                                              0

     env_78_wat_Watersheds_RetDisp_Mandrare  \
0                                         0
1                                         0
2                                         0
3                                         0
4                                         0
..                                      ...
521                                       0
522                                       0
523                                       0
524                                       0
525                                       0

     env_78_wat_Watersheds_RetDisp_Mangoky  \
0                                        0
1                                        0
2                                        0
3                                        0
4                                        0
..                                     ...
521                                      0
522                                      0
523                                      0
524                                      0
525                                      0

     env_78_wat_Watersheds_RetDisp_Mangoro  \
0                                        0
1                                        0
2                                        0
3                                        0
4                                        0
..                                     ...
521                                      0
522                                      0
523                                      0
524                                      0
525                                      0

     env_78_wat_Watersheds_RetDisp_Onilahy  \
0                                        0
1                                        0
2                                        0
3                                        0
4                                        0
..                                     ...
521                                      0
522                                      0
523                                      0
524                                      0
525                                      0

     env_78_wat_Watersheds_RetDisp_Sambirano  \
0                                          0
1                                          0
2                                          0
3                                          0
4                                          0
..                                       ...
521                                        0
522                                        0
523                                        0
524                                        0
525                                        0

     env_78_wat_Watersheds_RetDisp_Tsiribihina  env_78_wat_Watersheds__nodata
0                                            0                              0
1                                            0                              0
2                                            0                              0
3                                            0                              0
4                                            0                              0
..                                         ...                            ...
521                                          0                              0
522                                          0                              0
523                                          0                              0
524                                          0                              0
525                                          0                              0

[526 rows x 167 columns]>

In [15]:
coffee_data.drop(coffee_data.columns[0], axis=1, inplace=True)
coffee_data.head

<bound method NDFrame.head of         specimen_id  source_crs  longitude   latitude  \
0       humbertii_4        4326  43.797500 -22.875000
1     richardii_256        4326  50.041667 -14.101389
2      perrieri_261        4326  46.333889 -24.560833
3      perrieri_262        4326  46.333889 -24.560833
4      perrieri_263        4326  46.333889 -24.560833
..              ...         ...        ...        ...
521   resinosa_2807        4326  47.000000 -23.000000
522   resinosa_2809        4326  48.700000 -13.580000
523   dubardii_2812        4326  49.700000 -13.180000
524   dubardii_2813        4326  49.700000 -13.180000
525  humbertii_2814        4326  44.580000 -22.920000

                                  mada_geom_point  sampled_layers  \
0     POINT (376646.4194813568 7469814.360957881)              79
1    POINT (1044838.0523195444 8435209.185751595)              79
2     POINT (635084.8917711123 7283025.482374048)              79
3     POINT (635084.8917711123 7283025.482374048)              79
4     POINT (635084.8917711123 7283025.482374048)              79
..                                            ...             ...
521   POINT (704992.1724866081 7455081.895663038)              79
522   POINT (900530.2787016315 8495683.113346167)              79
523  POINT (1009820.5473967544 8538182.939559158)              79
524  POINT (1009820.5473967544 8538182.939559158)              79
525   POINT (456932.1646449176 7465274.693208166)              79

     nodata_layers  is_categorical_encoded  \
0                0                    True
1                0                    True
2                0                    True
3                0                    True
4                0                    True
..             ...                     ...
521              0                    True
522              0                    True
523              0                    True
524              0                    True
525              0                    True

     clim_1_tmin1_Monthly minimum temperature - January (°C x 10)  \
0                                                199.0
1                                                217.5
2                                                203.0
3                                                203.0
4                                                203.0
..                                                 ...
521                                              192.5
522                                              225.0
523                                              225.0
524                                              225.0
525                                              192.5

     clim_2_tmin2_Monthly minimum temperature - February (°C x 10)  ...  \
0                                                198.0              ...
1                                                218.0              ...
2                                                203.0              ...
3                                                203.0              ...
4                                                203.0              ...
..                                                 ...              ...
521                                              192.0              ...
522                                              226.0              ...
523                                              225.0              ...
524                                              225.0              ...
525                                              192.0              ...

     env_78_wat_Watersheds_RetDisp_Mahavavy  \
0                                         0
1                                         0
2                                         0
3                                         0
4                                         0
..                                      ...
521                                       0
522                                       0
523                                       0
524                                       0
525                                       0

     env_78_wat_Watersheds_RetDisp_Manampatrana  \
0                                             0
1                                             0
2                                             0
3                                             0
4                                             0
..                                          ...
521                                           0
522                                           0
523                                           0
524                                           0
525                                           0

     env_78_wat_Watersheds_RetDisp_Mananara_du_Sud  \
0                                                0
1                                                0
2                                                0
3                                                0
4                                                0
..                                             ...
521                                              1
522                                              0
523                                              0
524                                              0
525                                              0

     env_78_wat_Watersheds_RetDisp_Mandrare  \
0                                         0
1                                         0
2                                         0
3                                         0
4                                         0
..                                      ...
521                                       0
522                                       0
523                                       0
524                                       0
525                                       0

     env_78_wat_Watersheds_RetDisp_Mangoky  \
0                                        0
1                                        0
2                                        0
3                                        0
4                                        0
..                                     ...
521                                      0
522                                      0
523                                      0
524                                      0
525                                      0

     env_78_wat_Watersheds_RetDisp_Mangoro  \
0                                        0
1                                        0
2                                        0
3                                        0
4                                        0
..                                     ...
521                                      0
522                                      0
523                                      0
524                                      0
525                                      0

     env_78_wat_Watersheds_RetDisp_Onilahy  \
0                                        0
1                                        0
2                                        0
3                                        0
4                                        0
..                                     ...
521                                      0
522                                      0
523                                      0
524                                      0
525                                      0

     env_78_wat_Watersheds_RetDisp_Sambirano  \
0                                          0
1                                          0
2                                          0
3                                          0
4                                          0
..                                       ...
521                                        0
522                                        0
523                                        0
524                                        0
525                                        0

     env_78_wat_Watersheds_RetDisp_Tsiribihina  env_78_wat_Watersheds__nodata
0                                            0                              0
1                                            0                              0
2                                            0                              0
3                                            0                              0
4                                            0                              0
..                                         ...                            ...
521                                          0                              0
522                                          0                              0
523                                          0                              0
524                                          0                              0
525                                          0                              0

[526 rows x 166 columns]>

In [16]:
caffeine_content

               Species_name  caffeine_percent
0   C_andrambovatensis_A310             0.000
1          C_abbayesii_A601             0.000
2         C_arenesiana_A403             0.000
3           C_bertrandii_A5             0.000
4           C_dubardii_A969             0.000
5             C_heimii_A516             0.000
6        C_humbertii_RNF785             0.000
7           C_millotii_A222             0.000
8            C_perrieri_A12             0.000
9        C_pervilleana_A957             0.000
10            C_resinosa_A8             0.000
11        C_tsirananae_A515             0.000
12     C_vatovavyensis_A830             0.010
13            C_leroyi_A315             0.020
14     C_dolichophylla_A206             0.030
15   C_ambodirianensis_A572             0.030
16         C_richardii_A575             0.030
17         C_tetragona_A252             0.030
18     C_mauritiana_BM17_25             0.035
19      C_mauritiana_Makes4             0.035
20          C_vianneyi_A946             0.040
21   C_farafanganensis_A208             0.045
22          C_homollei_A945             0.060
23    C_kianjavatensis_A602             0.700
24        C_lancifolia_A320             0.700

In [17]:
# binary classification: 0 if caffeine_percent is 0 (or below), 1 if above 0
caffeine_content['caffeine_class'] = (caffeine_content['caffeine_percent'] > 0).astype(int)

print(caffeine_content)

               Species_name  caffeine_percent  caffeine_class
0   C_andrambovatensis_A310             0.000               0
1          C_abbayesii_A601             0.000               0
2         C_arenesiana_A403             0.000               0
3           C_bertrandii_A5             0.000               0
4           C_dubardii_A969             0.000               0
5             C_heimii_A516             0.000               0
6        C_humbertii_RNF785             0.000               0
7           C_millotii_A222             0.000               0
8            C_perrieri_A12             0.000               0
9        C_pervilleana_A957             0.000               0
10            C_resinosa_A8             0.000               0
11        C_tsirananae_A515             0.000               0
12     C_vatovavyensis_A830             0.010               1
13            C_leroyi_A315             0.020               1
14     C_dolichophylla_A206             0.030               1
15   C_ambodirianensis_A572             0.030               1
16         C_richardii_A575             0.030               1
17         C_tetragona_A252             0.030               1
18     C_mauritiana_BM17_25             0.035               1
19      C_mauritiana_Makes4             0.035               1
20          C_vianneyi_A946             0.040               1
21   C_farafanganensis_A208             0.045               1
22          C_homollei_A945             0.060               1
23    C_kianjavatensis_A602             0.700               1
24        C_lancifolia_A320             0.700               1

In [18]:
coffee_data['extracted_specimen'] = coffee_data['specimen_id'].str.split('_').str[0]
print(coffee_data.head)

<bound method NDFrame.head of         specimen_id  source_crs  longitude   latitude  \
0       humbertii_4        4326  43.797500 -22.875000
1     richardii_256        4326  50.041667 -14.101389
2      perrieri_261        4326  46.333889 -24.560833
3      perrieri_262        4326  46.333889 -24.560833
4      perrieri_263        4326  46.333889 -24.560833
..              ...         ...        ...        ...
521   resinosa_2807        4326  47.000000 -23.000000
522   resinosa_2809        4326  48.700000 -13.580000
523   dubardii_2812        4326  49.700000 -13.180000
524   dubardii_2813        4326  49.700000 -13.180000
525  humbertii_2814        4326  44.580000 -22.920000

                                  mada_geom_point  sampled_layers  \
0     POINT (376646.4194813568 7469814.360957881)              79
1    POINT (1044838.0523195444 8435209.185751595)              79
2     POINT (635084.8917711123 7283025.482374048)              79
3     POINT (635084.8917711123 7283025.482374048)              79
4     POINT (635084.8917711123 7283025.482374048)              79
..                                            ...             ...
521   POINT (704992.1724866081 7455081.895663038)              79
522   POINT (900530.2787016315 8495683.113346167)              79
523  POINT (1009820.5473967544 8538182.939559158)              79
524  POINT (1009820.5473967544 8538182.939559158)              79
525   POINT (456932.1646449176 7465274.693208166)              79

     nodata_layers  is_categorical_encoded  \
0                0                    True
1                0                    True
2                0                    True
3                0                    True
4                0                    True
..             ...                     ...
521              0                    True
522              0                    True
523              0                    True
524              0                    True
525              0                    True

     clim_1_tmin1_Monthly minimum temperature - January (°C x 10)  \
0                                                199.0
1                                                217.5
2                                                203.0
3                                                203.0
4                                                203.0
..                                                 ...
521                                              192.5
522                                              225.0
523                                              225.0
524                                              225.0
525                                              192.5

     clim_2_tmin2_Monthly minimum temperature - February (°C x 10)  ...  \
0                                                198.0              ...
1                                                218.0              ...
2                                                203.0              ...
3                                                203.0              ...
4                                                203.0              ...
..                                                 ...              ...
521                                              192.0              ...
522                                              226.0              ...
523                                              225.0              ...
524                                              225.0              ...
525                                              192.0              ...

     env_78_wat_Watersheds_RetDisp_Manampatrana  \
0                                             0
1                                             0
2                                             0
3                                             0
4                                             0
..                                          ...
521                                           0
522                                           0
523                                           0
524                                           0
525                                           0

     env_78_wat_Watersheds_RetDisp_Mananara_du_Sud  \
0                                                0
1                                                0
2                                                0
3                                                0
4                                                0
..                                             ...
521                                              1
522                                              0
523                                              0
524                                              0
525                                              0

     env_78_wat_Watersheds_RetDisp_Mandrare  \
0                                         0
1                                         0
2                                         0
3                                         0
4                                         0
..                                      ...
521                                       0
522                                       0
523                                       0
524                                       0
525                                       0

     env_78_wat_Watersheds_RetDisp_Mangoky  \
0                                        0
1                                        0
2                                        0
3                                        0
4                                        0
..                                     ...
521                                      0
522                                      0
523                                      0
524                                      0
525                                      0

     env_78_wat_Watersheds_RetDisp_Mangoro  \
0                                        0
1                                        0
2                                        0
3                                        0
4                                        0
..                                     ...
521                                      0
522                                      0
523                                      0
524                                      0
525                                      0

     env_78_wat_Watersheds_RetDisp_Onilahy  \
0                                        0
1                                        0
2                                        0
3                                        0
4                                        0
..                                     ...
521                                      0
522                                      0
523                                      0
524                                      0
525                                      0

     env_78_wat_Watersheds_RetDisp_Sambirano  \
0                                          0
1                                          0
2                                          0
3                                          0
4                                          0
..                                       ...
521                                        0
522                                        0
523                                        0
524                                        0
525                                        0

     env_78_wat_Watersheds_RetDisp_Tsiribihina  env_78_wat_Watersheds__nodata  \
0                                            0                              0
1                                            0                              0
2                                            0                              0
3                                            0                              0
4                                            0                              0
..                                         ...                            ...
521                                          0                              0
522                                          0                              0
523                                          0                              0
524                                          0                              0
525                                          0                              0

     extracted_specimen
0             humbertii
1             richardii
2              perrieri
3              perrieri
4              perrieri
..                  ...
521            resinosa
522            resinosa
523            dubardii
524            dubardii
525           humbertii

[526 rows x 167 columns]>

In [19]:
caffeine_content['extracted_species'] = caffeine_content['Species_name'].str.split('_').str[1]
print(caffeine_content)

               Species_name  caffeine_percent  caffeine_class  \
0   C_andrambovatensis_A310             0.000               0
1          C_abbayesii_A601             0.000               0
2         C_arenesiana_A403             0.000               0
3           C_bertrandii_A5             0.000               0
4           C_dubardii_A969             0.000               0
5             C_heimii_A516             0.000               0
6        C_humbertii_RNF785             0.000               0
7           C_millotii_A222             0.000               0
8            C_perrieri_A12             0.000               0
9        C_pervilleana_A957             0.000               0
10            C_resinosa_A8             0.000               0
11        C_tsirananae_A515             0.000               0
12     C_vatovavyensis_A830             0.010               1
13            C_leroyi_A315             0.020               1
14     C_dolichophylla_A206             0.030               1
15   C_ambodirianensis_A572             0.030               1
16         C_richardii_A575             0.030               1
17         C_tetragona_A252             0.030               1
18     C_mauritiana_BM17_25             0.035               1
19      C_mauritiana_Makes4             0.035               1
20          C_vianneyi_A946             0.040               1
21   C_farafanganensis_A208             0.045               1
22          C_homollei_A945             0.060               1
23    C_kianjavatensis_A602             0.700               1
24        C_lancifolia_A320             0.700               1

   extracted_species
0   andrambovatensis
1          abbayesii
2         arenesiana
3         bertrandii
4           dubardii
5             heimii
6          humbertii
7           millotii
8           perrieri
9        pervilleana
10          resinosa
11        tsirananae
12     vatovavyensis
13            leroyi
14     dolichophylla
15   ambodirianensis
16         richardii
17         tetragona
18        mauritiana
19        mauritiana
20          vianneyi
21   farafanganensis
22          homollei
23    kianjavatensis
24        lancifolia

In [20]:
merged_df = pd.merge(
    coffee_data,
    caffeine_content[['extracted_species', 'caffeine_percent','caffeine_class']],
    left_on='extracted_specimen',
    right_on='extracted_species',
    how='left'  # Use 'left' join to keep all rows from coffee_env_data
)

# Step 4: Drop the helper columns
merged_df = merged_df.drop(columns=['extracted_specimen', 'extracted_species'])

# The result is the original DataFrame with an additional 'caffeine_class' column
merged_df.to_csv(r'../data/coll_caff_node_w_class.csv', index=False)

In [21]:
merged_df

,specimen_id,source_crs,longitude,latitude,mada_geom_point,sampled_layers,nodata_layers,is_categorical_encoded,clim_1_tmin1_Monthly minimum temperature - January (°C x 10),clim_2_tmin2_Monthly minimum temperature - February (°C x 10),...,env_78_wat_Watersheds_RetDisp_Mananara_du_Sud,env_78_wat_Watersheds_RetDisp_Mandrare,env_78_wat_Watersheds_RetDisp_Mangoky,env_78_wat_Watersheds_RetDisp_Mangoro,env_78_wat_Watersheds_RetDisp_Onilahy,env_78_wat_Watersheds_RetDisp_Sambirano,env_78_wat_Watersheds_RetDisp_Tsiribihina,env_78_wat_Watersheds__nodata,caffeine_percent,caffeine_class
0,humbertii_4,4326,43.797500,-22.875000,POINT (376646.4194813568 7469814.360957881),79,0,True,199.0,198.0,...,0,0,0,0,0,0,0,0,0.00,0
1,richardii_256,4326,50.041667,-14.101389,POINT (1044838.0523195444 8435209.185751595),79,0,True,217.5,218.0,...,0,0,0,0,0,0,0,0,0.03,1
2,perrieri_261,4326,46.333889,-24.560833,POINT (635084.8917711123 7283025.482374048),79,0,True,203.0,203.0,...,0,0,0,0,0,0,0,0,0.00,0
3,perrieri_262,4326,46.333889,-24.560833,POINT (635084.8917711123 7283025.482374048),79,0,True,203.0,203.0,...,0,0,0,0,0,0,0,0,0.00,0
4,perrieri_263,4326,46.333889,-24.560833,POINT (635084.8917711123 7283025.482374048),79,0,True,203.0,203.0,...,0,0,0,0,0,0,0,0,0.00,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
521,resinosa_2807,4326,47.000000,-23.000000,POINT (704992.1724866081 7455081.895663038),79,0,True,192.5,192.0,...,1,0,0,0,0,0,0,0,0.00,0
522,resinosa_2809,4326,48.700000,-13.580000,POINT (900530.2787016315 8495683.113346167),79,0,True,225.0,226.0,...,0,0,0,0,0,0,0,0,0.00,0
523,dubardii_2812,4326,49.700000,-13.180000,POINT (1009820.5473967544 8538182.939559158),79,0,True,225.0,225.0,...,0,0,0,0,0,0,0,0,0.00,0
524,dubardii_2813,4326,49.700000,-13.180000,POINT (1009820.5473967544 8538182.939559158),79,0,True,225.0,225.0,...,0,0,0,0,0,0,0,0,0.00,0
525,humbertii_2814,4326,44.580000,-22.920000,POINT (456932.1646449176 7465274.693208166),79,0,True,192.5,192.0,...,0,0,0,0,0,0,0,0,0.00,0