In [5]:
import sklearn
import numpy as np
import scipy as sp
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import re

In [28]:
pd.set_option('display.max_colwidth', None)
pd.set_option('display.width', 1000)
pd.set_option('display.expand_frame_repr', False)  # Disable line-wrapping
pd.set_option('display.max_rows', 20)

In [29]:
#coffee_clim_data = pd.read_csv(r"..\data\coll_caff_node_clim.csv")
#coffee_env_data = pd.read_csv(r"..\data\coll_caff_node_env.csv")
coffee_data = pd.read_csv(r"..\data\coll_all_new_jan.csv")
coffee_data_bin = pd.read_csv(r"..\data\coll_all_new_jan_bin.csv")

caffeine_content = pd.read_csv(r"..\input\no_caffeine_nodes_w_specimen.csv")

coffee_data.head

<bound method NDFrame.head of             specimen_id  source_crs  longitude   latitude                              mada_geom_point  sampled_layers  nodata_layers  is_categorical_encoded         specimen_name  clim_1_tmin1_jan  ...  env_73_asp  env_74_solrad  env_75_geo  env_76_soi  env_77_veg  env_78_wat  env_79_forcov  clim_1_tmin1_jan_old  clim_13_tmax1_jan_old  clim_25_prec1_jan_old
0           abbayesii_0        4326  46.450000 -24.366660  POINT (647070.6204618097 7304410.220689219)              79              0                   False      Coffea_abbayesii             195.5  ...       307.0         7430.0        10.0         6.0         7.0         6.0            0.0                 159.0                  307.0                   30.0
1           abbayesii_1        4326  46.830000 -24.730000  POINT (685086.8720605411 7263711.610572983)              79              0                   False      Coffea_abbayesii             177.5  ...        56.0         7630.0        10.0         9.0        14.0         5.0          100.0                 139.0                  260.0                   52.0
2           abbayesii_2        4326  46.833300 -24.733300   POINT (685415.815086571 7263341.630764661)              79              0                   False      Coffea_abbayesii             177.5  ...        56.0         7630.0        10.0         9.0        14.0         5.0          100.0                 139.0                  260.0                   52.0
3           abbayesii_3        4326  46.833330 -24.666670  POINT (685517.5605412831 7270721.614432366)              79              0                   False      Coffea_abbayesii             208.5  ...        48.0         7595.0        10.0        10.0         7.0         5.0            0.0                 168.0                  292.0                   61.0
4           abbayesii_4        4326  46.833333 -24.733333  POINT (685419.1044266553 7263337.930920706)              79              0                   False      Coffea_abbayesii             177.5  ...        56.0         7630.0        10.0         9.0        14.0         5.0          100.0                 139.0                  260.0                   52.0
..                  ...         ...        ...        ...                                          ...             ...            ...                     ...                   ...               ...  ...         ...            ...         ...         ...         ...         ...            ...                   ...                    ...                    ...
463  vatovavyensis_3729        4326  47.866667 -21.383333   POINT (797253.6520891015 7632714.03380194)              79              0                   False  Coffea_vatovavyensis             216.0  ...        11.0         7706.0        10.0        11.0        16.0         3.0            0.0                 178.0                  276.0                   71.0
464  vatovavyensis_3730        4326  47.933333 -21.400000  POINT (804136.3625319668 7630739.814647073)              79              0                   False  Coffea_vatovavyensis             208.0  ...       347.0         8061.0        10.0        11.0        16.0         3.0           18.0                 170.0                  267.0                   69.0
465       vianneyi_3732        4326  47.863972 -21.382389  POINT (796975.9344399704 7632823.713043112)              79              0                   False       Coffea_vianneyi             211.0  ...        48.0         7777.0        10.0        11.0        16.0         3.0            0.0                 173.0                  273.0                   69.0
466       vianneyi_3733        4326  47.866667 -21.383333   POINT (797253.6520891015 7632714.03380194)              79              0                   False       Coffea_vianneyi             216.0  ...        11.0         7706.0        10.0        11.0        16.0         3.0            0.0                 178.0                  276.0                   71.0
467       vianneyi_3734        4326  47.867861 -21.377889   POINT (797388.5523752098 7633314.85921484)              79              0                   False       Coffea_vianneyi             214.0  ...       173.0         6717.0        10.0        11.0        16.0         3.0           16.0                 176.0                  275.0                   70.0

[468 rows x 91 columns]>

In [30]:
caffeine_content

               Species_name  caffeine_percent
0   C_andrambovatensis_A310             0.000
1          C_abbayesii_A601             0.000
2         C_arenesiana_A403             0.000
3           C_bertrandii_A5             0.000
4           C_dubardii_A969             0.000
..                      ...               ...
21          C_vianneyi_A946             0.040
22   C_farafanganensis_A208             0.045
23          C_homollei_A945             0.060
24    C_kianjavatensis_A602             0.700
25        C_lancifolia_A320             0.700

[26 rows x 2 columns]

In [9]:
coffee_data.drop(coffee_data.columns[0], axis=1, inplace=True)
coffee_data.head

<bound method NDFrame.head of      source_crs  longitude   latitude                                mada_geom_point  sampled_layers  nodata_layers  is_categorical_encoded            specimen_name  clim_1_tmin1_jan  clim_2_tmin2_feb  ...  env_73_asp  env_74_solrad  env_75_geo  env_76_soi  env_77_veg  env_78_wat  env_79_forcov  clim_1_tmin1_jan_old  clim_13_tmax1_jan_old  clim_25_prec1_jan_old
0          4326  46.450000 -24.366660    POINT (647070.6204618097 7304410.220689219)              79              0                   False         Coffea_abbayesii             195.5             195.0  ...       307.0         7430.0        10.0         6.0         7.0         6.0            0.0                 159.0                  307.0                   30.0
1          4326  46.830000 -24.730000    POINT (685086.8720605411 7263711.610572983)              79              0                   False         Coffea_abbayesii             177.5             177.0  ...        56.0         7630.0        10.0         9.0        14.0         5.0          100.0                 139.0                  260.0                   52.0
2          4326  46.833300 -24.733300     POINT (685415.815086571 7263341.630764661)              79              0                   False         Coffea_abbayesii             177.5             177.0  ...        56.0         7630.0        10.0         9.0        14.0         5.0          100.0                 139.0                  260.0                   52.0
3          4326  46.833330 -24.666670    POINT (685517.5605412831 7270721.614432366)              79              0                   False         Coffea_abbayesii             208.5             208.0  ...        48.0         7595.0        10.0        10.0         7.0         5.0            0.0                 168.0                  292.0                   61.0
4          4326  46.833333 -24.733333    POINT (685419.1044266553 7263337.930920706)              79              0                   False         Coffea_abbayesii             177.5             177.0  ...        56.0         7630.0        10.0         9.0        14.0         5.0          100.0                 139.0                  260.0                   52.0
5          4326  46.850000 -24.800000     POINT (687005.230680173 7255931.021614572)              79              0                   False         Coffea_abbayesii             214.0             214.0  ...       240.0         7212.0        10.0        10.0         7.0         5.0            0.0                 172.0                  287.0                   67.0
6          4326  46.863333 -24.760833    POINT (688412.4477942145 7260250.968656886)              79              0                   False         Coffea_abbayesii             195.5             195.0  ...       167.0         6475.0        10.0         9.0        14.0         5.0          100.0                 155.0                  276.0                   57.0
7          4326  46.962222 -24.836667    POINT (698293.4731815766 7251711.088876668)              79              0                   False         Coffea_abbayesii             194.5             194.0  ...       282.0         7315.0        10.0         9.0        14.0         5.0           99.0                 155.0                  266.0                   65.0
8          4326  47.136111 -24.842778    POINT (715860.4092442521 7250769.964015225)              79              1                   False         Coffea_abbayesii             216.5             215.0  ...       311.0         7362.0         NaN        21.0         7.0         5.0           18.0                 178.0                  272.0                   96.0
9          4326  47.136667 -24.835833    POINT (715928.6693715989 7251538.425058084)              79              0                   False         Coffea_abbayesii             217.0             216.0  ...       120.0         7187.0         2.0        21.0         7.0         5.0            7.0                 177.0                  272.0                   96.0
10         4326  47.140100 -24.835216     POINT (716276.781554349 7251601.331429132)              79              5                   False         Coffea_abbayesii             217.0             216.0  ...         NaN            NaN         NaN         NaN        15.0         5.0           48.0                 178.0                  272.0                   97.0
11         4326  47.166111 -24.796389    POINT (718974.5237810896 7255860.966205925)              79              0                   False         Coffea_abbayesii             216.5             216.0  ...       246.0         7250.0         2.0        21.0         6.0         5.0           18.0                 178.0                  273.0                   99.0
12         4326  47.863889 -21.382500   POINT (796967.0982798996 7632811.5735395495)              79              0                   False         Coffea_abbayesii             211.0             210.0  ...        48.0         7777.0        10.0        11.0        16.0         3.0            0.0                 173.0                  273.0                   69.0
13         4326  47.866667 -21.383333     POINT (797253.6520891015 7632714.03380194)              79              0                   False         Coffea_abbayesii             216.0             215.0  ...        11.0         7706.0        10.0        11.0        16.0         3.0            0.0                 178.0                  276.0                   71.0
14         4326  47.867861 -21.377889     POINT (797388.5523752098 7633314.85921484)              79              0                   False         Coffea_abbayesii             214.0             213.0  ...       173.0         6717.0        10.0        11.0        16.0         3.0           16.0                 176.0                  275.0                   70.0
15         4326  47.750000 -21.516667    POINT (784889.6338244496 7618160.762740698)              79              0                   False  Coffea_andrambovatensis             200.5             200.0  ...       191.0         7580.0        10.0        11.0        16.0         3.0            0.0                 162.0                  267.0                   62.0
16         4326  47.758333 -21.525000    POINT (785737.0767059072 7617222.442619566)              79              0                   False  Coffea_andrambovatensis             206.5             205.0  ...       267.0         7456.0        10.0        11.0        16.0         3.0            0.0                 168.0                  270.0                   64.0
17         4326  47.866667 -21.383333     POINT (797253.6520891015 7632714.03380194)              79              0                   False  Coffea_andrambovatensis             216.0             215.0  ...        11.0         7706.0        10.0        11.0        16.0         3.0            0.0                 178.0                  276.0                   71.0
18         4326  47.533100 -18.939287    POINT (766774.1131943119 7903975.383623635)              79              0                   False        Coffea_arenesiana             161.5             162.0  ...       289.0         7911.0         1.0        10.0         4.0        20.0            0.0                 121.0                  254.0                   48.0
19         4326  47.928889 -18.919722    POINT (808519.6229292486 7905496.676447506)              79              0                   False        Coffea_arenesiana             161.0             161.0  ...       338.0         7929.0        10.0         9.0        14.0        15.0           33.0                 119.0                  247.0                   46.0
20         4326  48.033333 -18.883333    POINT (819598.6437374875 7909341.577006979)              79              0                   False        Coffea_arenesiana             177.0             177.0  ...       148.0         7785.0         1.0        12.0         6.0        15.0            0.0                 134.0                  267.0                   46.0
21         4326  48.216667 -19.177222    POINT (838334.1604373527 7876441.048947236)              79              0                   False        Coffea_arenesiana             170.0             171.0  ...       189.0         7711.0        10.0         9.0        14.0         2.0           62.0                 123.0                  246.0                   47.0
22         4326  48.228611 -19.177222    POINT (839591.4978414372 7876417.793199601)              79              0                   False        Coffea_arenesiana             170.5             172.0  ...       139.0         7753.0        10.0         9.0        14.0         2.0           27.0                 124.0                  247.0                   47.0
23         4326  48.254139 -19.120401    POINT (842396.2634442383 7882663.036728507)              79              0                   False        Coffea_arenesiana             172.5             174.0  ...       202.0         7838.0        10.0         9.0        16.0         2.0            0.0                 126.0                  250.0                   47.0
24         4326  48.275000 -18.950000    POINT (844945.4580991727 7901500.991120957)              79              0                   False        Coffea_arenesiana             170.0             171.0  ...       240.0         7515.0        10.0         9.0        16.0         2.0            5.0                 124.0                  250.0                   45.0
25         4326  46.486576 -24.820319    POINT (650238.3690614552 7254129.565000778)              79              0                   False        Coffea_bertrandii             210.5             211.0  ...       115.0         7232.0        10.0         6.0        12.0         6.0          100.0                 163.0                  315.0                   34.0
26         4326  46.633330 -25.016660    POINT (664811.0648534158 7232213.926725963)              79              0                   False        Coffea_bertrandii             214.0             214.0  ...       353.0         7301.0        10.0         6.0         7.0         5.0           84.0                 167.0                  299.0                   39.0
27         4326  46.639722 -25.023333   POINT (665447.2146653433 7231467.0431410335)              79              0                   False        Coffea_bertrandii             213.0             213.0  ...       316.0         7346.0        10.0         6.0         7.0         5.0           79.0                 166.0                  296.0                   40.0
28         4326  46.666660 -25.033330    POINT (668152.1082198943 7230326.594352566)              79              0                   False        Coffea_bertrandii             214.0             214.0  ...       189.0         6765.0        10.0         9.0         7.0         5.0           20.0                 169.0                  295.0                   42.0
29         4326  46.674722 -25.122222    POINT (668843.6342847437 7220470.852634992)              79              0                   False        Coffea_bertrandii             219.0             219.0  ...       119.0         6517.0        10.0        15.0         7.0         5.0           88.0                 172.0                  293.0                   41.0
30         4326  46.683330 -25.066670      POINT (669788.333901034 7226613.03440059)              79              0                   False        Coffea_bertrandii             219.0             219.0  ...         9.0         7562.0        10.0        10.0         7.0         5.0           29.0                 173.0                  295.0                   43.0
31         4326  46.683333 -25.066667     POINT (669788.640688142 7226613.362913565)              79              0                   False        Coffea_bertrandii             219.0             219.0  ...         9.0         7562.0        10.0        10.0         7.0         5.0           29.0                 173.0                  295.0                   43.0
32         4326  46.758330 -25.150000     POINT (677234.4440133531 7217286.77883262)              79              0                   False        Coffea_bertrandii             219.5             219.0  ...       284.0         7298.0         1.0        21.0         4.0         5.0            3.0                 175.0                  283.0                   48.0
33         4326  47.866667 -21.383333     POINT (797253.6520891015 7632714.03380194)              79              0                   False        Coffea_bertrandii             216.0             215.0  ...        11.0         7706.0        10.0        11.0        16.0         3.0            0.0                 178.0                  276.0                   71.0
34         4326  44.732222 -16.931667   POINT (471486.44712923677 8127984.871431336)              79              0                   False          Coffea_dubardii             228.0             229.0  ...        52.0         7811.0         9.0        18.0         5.0         8.0           49.0                 204.0                  333.0                   23.0
35         4326  44.749166 -16.958611  POINT (473294.49236259685 8125006.5619353615)              79              0                   False          Coffea_dubardii             221.5             222.0  ...       141.0         7620.0         9.0        18.0         5.0         8.0           71.0                 198.0                  328.0                   25.0
36         4326  44.749167 -16.958611   POINT (473294.59883002134 8125006.562071315)              79              0                   False          Coffea_dubardii             221.5             222.0  ...       141.0         7620.0         9.0        18.0         5.0         8.0           71.0                 198.0                  328.0                   25.0
37         4326  47.233333 -15.066667    POINT (740078.3644282935 8333083.596531117)              79              0                   False          Coffea_dubardii             231.0             230.0  ...       227.0         7632.0         5.0        20.0         5.0         9.0           62.0                 208.0                  339.0                   22.0
38         4326  47.266667 -15.016667    POINT (743720.1593233433 8338580.996401502)              79              0                   False          Coffea_dubardii             233.0             232.0  ...       135.0         7768.0         5.0        20.0         3.0         9.0           72.0                 211.0                  340.0                   23.0
39         4326  47.863889 -21.382500   POINT (796967.0982798996 7632811.5735395495)              79              0                   False          Coffea_dubardii             211.0             210.0  ...        48.0         7777.0        10.0        11.0        16.0         3.0            0.0                 173.0                  273.0                   69.0
40         4326  47.863972 -21.382389    POINT (796975.9344399704 7632823.713043112)              79              0                   False          Coffea_dubardii             211.0             210.0  ...        48.0         7777.0        10.0        11.0        16.0         3.0            0.0                 173.0                  273.0                   69.0
41         4326  47.867500 -21.375833    POINT (797355.2531098193 7633543.307278467)              79              0                   False          Coffea_dubardii             214.0             213.0  ...       173.0         6717.0        10.0        11.0        16.0         3.0           16.0                 176.0                  275.0                   70.0
42         4326  49.055556 -12.922222    POINT (940259.7556518493 8567976.697977759)              79              0                   False          Coffea_dubardii             232.5             233.0  ...       204.0         7830.0         7.0        22.0         7.0        13.0           17.0                 215.0                  322.0                   30.0
43         4326  49.066667 -12.850000    POINT (941594.6956003106 8575962.476910887)              79              0                   False          Coffea_dubardii             230.0             230.0  ...       193.0         7763.0         9.0         8.0         7.0        12.0           17.0                 212.0                  316.0                   28.0
44         4326  49.072222 -12.932500    POINT (942053.5831398848 8566808.703762723)              79              0                   False          Coffea_dubardii             226.5             227.0  ...       161.0         7603.0         7.0        22.0         2.0        13.0           10.0                 208.0                  317.0                   29.0
45         4326  49.083330 -12.500000    POINT (944014.5765139057 8614727.573604858)              79              0                   False          Coffea_dubardii             211.5             212.0  ...       352.0         8040.0         9.0        18.0         7.0        12.0            0.0                 190.0                  288.0                   19.0
46         4326  49.083333 -12.900000    POINT (943319.0546159232 8570391.744125314)              79              0                   False          Coffea_dubardii             226.5             227.0  ...       358.0         7892.0         7.0        22.0         5.0        13.0           12.0                 208.0                  316.0                   29.0
47         4326  49.100000 -12.900000    POINT (945131.3540197855 8570362.800563525)              79              0                   False          Coffea_dubardii             225.5             226.0  ...       142.0         7785.0         7.0        22.0         2.0        13.0            8.0                 207.0                  315.0                   28.0
48         4326  49.105000 -12.846388    POINT (945770.0611607116 8576296.608845381)              79              0                   False          Coffea_dubardii             225.5             226.0  ...       206.0         7872.0         9.0         8.0         7.0        12.0           13.0                 207.0                  313.0                   27.0
49         4326  49.105000 -12.846390    POINT (945770.0576231861 8576296.387159621)              79              0                   False          Coffea_dubardii             225.5             226.0  ...       206.0         7872.0         9.0         8.0         7.0        12.0           13.0                 207.0                  313.0                   27.0
50         4326  49.105000 -12.846400     POINT (945770.0399355507 8576295.27873082)              79              0                   False          Coffea_dubardii             225.5             226.0  ...       206.0         7872.0         9.0         8.0         7.0        12.0           13.0                 207.0                  313.0                   27.0
51         4326  49.106660 -12.916380    POINT (945826.4226579209 8568535.587778185)              79              0                   False          Coffea_dubardii             227.5             228.0  ...       297.0         7900.0         7.0        22.0         5.0        13.0           56.0                 209.0                  317.0                   29.0
52         4326  49.106667 -12.916389    POINT (945827.1677606131 8568534.577972405)              79              0                   False          Coffea_dubardii             227.5             228.0  ...       297.0         7900.0         7.0        22.0         5.0        13.0           56.0                 209.0                  317.0                   29.0

In [10]:
caffeine_content

               Species_name  caffeine_percent
0   C_andrambovatensis_A310             0.000
1          C_abbayesii_A601             0.000
2         C_arenesiana_A403             0.000
3           C_bertrandii_A5             0.000
4           C_dubardii_A969             0.000
5             C_heimii_A516             0.000
6        C_humbertii_RNF785             0.000
7     C_humblotiana_BM19_20             0.000
8           C_millotii_A222             0.000
9            C_perrieri_A12             0.000
10       C_pervilleana_A957             0.000
11            C_resinosa_A8             0.000
12        C_tsirananae_A515             0.000
13     C_vatovavyensis_A830             0.010
14            C_leroyi_A315             0.020
15     C_dolichophylla_A206             0.030
16   C_ambodirianensis_A572             0.030
17         C_richardii_A575             0.030
18         C_tetragona_A252             0.030
19     C_mauritiana_BM17_25             0.035
20      C_mauritiana_Makes4             0.035
21          C_vianneyi_A946             0.040
22   C_farafanganensis_A208             0.045
23          C_homollei_A945             0.060
24    C_kianjavatensis_A602             0.700
25        C_lancifolia_A320             0.700

In [31]:
# binary classification: 0 if caffeine_percent is 0 (or below), 1 if above 0
caffeine_content['caffeine_class'] = (caffeine_content['caffeine_percent'] > 0).astype(int)

print(caffeine_content)

               Species_name  caffeine_percent  caffeine_class
0   C_andrambovatensis_A310             0.000               0
1          C_abbayesii_A601             0.000               0
2         C_arenesiana_A403             0.000               0
3           C_bertrandii_A5             0.000               0
4           C_dubardii_A969             0.000               0
..                      ...               ...             ...
21          C_vianneyi_A946             0.040               1
22   C_farafanganensis_A208             0.045               1
23          C_homollei_A945             0.060               1
24    C_kianjavatensis_A602             0.700               1
25        C_lancifolia_A320             0.700               1

[26 rows x 3 columns]

In [12]:
coffee_data['extracted_specimen'] = coffee_data['specimen_name'].str.split('_').str[1]
print(coffee_data.head)

<bound method NDFrame.head of      source_crs  longitude   latitude                                mada_geom_point  sampled_layers  nodata_layers  is_categorical_encoded            specimen_name  clim_1_tmin1_jan  clim_2_tmin2_feb  ...  env_74_solrad  env_75_geo  env_76_soi  env_77_veg  env_78_wat  env_79_forcov  clim_1_tmin1_jan_old  clim_13_tmax1_jan_old  clim_25_prec1_jan_old  extracted_specimen
0          4326  46.450000 -24.366660    POINT (647070.6204618097 7304410.220689219)              79              0                   False         Coffea_abbayesii             195.5             195.0  ...         7430.0        10.0         6.0         7.0         6.0            0.0                 159.0                  307.0                   30.0           abbayesii
1          4326  46.830000 -24.730000    POINT (685086.8720605411 7263711.610572983)              79              0                   False         Coffea_abbayesii             177.5             177.0  ...         7630.0        10.0         9.0        14.0         5.0          100.0                 139.0                  260.0                   52.0           abbayesii
2          4326  46.833300 -24.733300     POINT (685415.815086571 7263341.630764661)              79              0                   False         Coffea_abbayesii             177.5             177.0  ...         7630.0        10.0         9.0        14.0         5.0          100.0                 139.0                  260.0                   52.0           abbayesii
3          4326  46.833330 -24.666670    POINT (685517.5605412831 7270721.614432366)              79              0                   False         Coffea_abbayesii             208.5             208.0  ...         7595.0        10.0        10.0         7.0         5.0            0.0                 168.0                  292.0                   61.0           abbayesii
4          4326  46.833333 -24.733333    POINT (685419.1044266553 7263337.930920706)              79              0                   False         Coffea_abbayesii             177.5             177.0  ...         7630.0        10.0         9.0        14.0         5.0          100.0                 139.0                  260.0                   52.0           abbayesii
5          4326  46.850000 -24.800000     POINT (687005.230680173 7255931.021614572)              79              0                   False         Coffea_abbayesii             214.0             214.0  ...         7212.0        10.0        10.0         7.0         5.0            0.0                 172.0                  287.0                   67.0           abbayesii
6          4326  46.863333 -24.760833    POINT (688412.4477942145 7260250.968656886)              79              0                   False         Coffea_abbayesii             195.5             195.0  ...         6475.0        10.0         9.0        14.0         5.0          100.0                 155.0                  276.0                   57.0           abbayesii
7          4326  46.962222 -24.836667    POINT (698293.4731815766 7251711.088876668)              79              0                   False         Coffea_abbayesii             194.5             194.0  ...         7315.0        10.0         9.0        14.0         5.0           99.0                 155.0                  266.0                   65.0           abbayesii
8          4326  47.136111 -24.842778    POINT (715860.4092442521 7250769.964015225)              79              1                   False         Coffea_abbayesii             216.5             215.0  ...         7362.0         NaN        21.0         7.0         5.0           18.0                 178.0                  272.0                   96.0           abbayesii
9          4326  47.136667 -24.835833    POINT (715928.6693715989 7251538.425058084)              79              0                   False         Coffea_abbayesii             217.0             216.0  ...         7187.0         2.0        21.0         7.0         5.0            7.0                 177.0                  272.0                   96.0           abbayesii
10         4326  47.140100 -24.835216     POINT (716276.781554349 7251601.331429132)              79              5                   False         Coffea_abbayesii             217.0             216.0  ...            NaN         NaN         NaN        15.0         5.0           48.0                 178.0                  272.0                   97.0           abbayesii
11         4326  47.166111 -24.796389    POINT (718974.5237810896 7255860.966205925)              79              0                   False         Coffea_abbayesii             216.5             216.0  ...         7250.0         2.0        21.0         6.0         5.0           18.0                 178.0                  273.0                   99.0           abbayesii
12         4326  47.863889 -21.382500   POINT (796967.0982798996 7632811.5735395495)              79              0                   False         Coffea_abbayesii             211.0             210.0  ...         7777.0        10.0        11.0        16.0         3.0            0.0                 173.0                  273.0                   69.0           abbayesii
13         4326  47.866667 -21.383333     POINT (797253.6520891015 7632714.03380194)              79              0                   False         Coffea_abbayesii             216.0             215.0  ...         7706.0        10.0        11.0        16.0         3.0            0.0                 178.0                  276.0                   71.0           abbayesii
14         4326  47.867861 -21.377889     POINT (797388.5523752098 7633314.85921484)              79              0                   False         Coffea_abbayesii             214.0             213.0  ...         6717.0        10.0        11.0        16.0         3.0           16.0                 176.0                  275.0                   70.0           abbayesii
15         4326  47.750000 -21.516667    POINT (784889.6338244496 7618160.762740698)              79              0                   False  Coffea_andrambovatensis             200.5             200.0  ...         7580.0        10.0        11.0        16.0         3.0            0.0                 162.0                  267.0                   62.0    andrambovatensis
16         4326  47.758333 -21.525000    POINT (785737.0767059072 7617222.442619566)              79              0                   False  Coffea_andrambovatensis             206.5             205.0  ...         7456.0        10.0        11.0        16.0         3.0            0.0                 168.0                  270.0                   64.0    andrambovatensis
17         4326  47.866667 -21.383333     POINT (797253.6520891015 7632714.03380194)              79              0                   False  Coffea_andrambovatensis             216.0             215.0  ...         7706.0        10.0        11.0        16.0         3.0            0.0                 178.0                  276.0                   71.0    andrambovatensis
18         4326  47.533100 -18.939287    POINT (766774.1131943119 7903975.383623635)              79              0                   False        Coffea_arenesiana             161.5             162.0  ...         7911.0         1.0        10.0         4.0        20.0            0.0                 121.0                  254.0                   48.0          arenesiana
19         4326  47.928889 -18.919722    POINT (808519.6229292486 7905496.676447506)              79              0                   False        Coffea_arenesiana             161.0             161.0  ...         7929.0        10.0         9.0        14.0        15.0           33.0                 119.0                  247.0                   46.0          arenesiana
20         4326  48.033333 -18.883333    POINT (819598.6437374875 7909341.577006979)              79              0                   False        Coffea_arenesiana             177.0             177.0  ...         7785.0         1.0        12.0         6.0        15.0            0.0                 134.0                  267.0                   46.0          arenesiana
21         4326  48.216667 -19.177222    POINT (838334.1604373527 7876441.048947236)              79              0                   False        Coffea_arenesiana             170.0             171.0  ...         7711.0        10.0         9.0        14.0         2.0           62.0                 123.0                  246.0                   47.0          arenesiana
22         4326  48.228611 -19.177222    POINT (839591.4978414372 7876417.793199601)              79              0                   False        Coffea_arenesiana             170.5             172.0  ...         7753.0        10.0         9.0        14.0         2.0           27.0                 124.0                  247.0                   47.0          arenesiana
23         4326  48.254139 -19.120401    POINT (842396.2634442383 7882663.036728507)              79              0                   False        Coffea_arenesiana             172.5             174.0  ...         7838.0        10.0         9.0        16.0         2.0            0.0                 126.0                  250.0                   47.0          arenesiana
24         4326  48.275000 -18.950000    POINT (844945.4580991727 7901500.991120957)              79              0                   False        Coffea_arenesiana             170.0             171.0  ...         7515.0        10.0         9.0        16.0         2.0            5.0                 124.0                  250.0                   45.0          arenesiana
25         4326  46.486576 -24.820319    POINT (650238.3690614552 7254129.565000778)              79              0                   False        Coffea_bertrandii             210.5             211.0  ...         7232.0        10.0         6.0        12.0         6.0          100.0                 163.0                  315.0                   34.0          bertrandii
26         4326  46.633330 -25.016660    POINT (664811.0648534158 7232213.926725963)              79              0                   False        Coffea_bertrandii             214.0             214.0  ...         7301.0        10.0         6.0         7.0         5.0           84.0                 167.0                  299.0                   39.0          bertrandii
27         4326  46.639722 -25.023333   POINT (665447.2146653433 7231467.0431410335)              79              0                   False        Coffea_bertrandii             213.0             213.0  ...         7346.0        10.0         6.0         7.0         5.0           79.0                 166.0                  296.0                   40.0          bertrandii
28         4326  46.666660 -25.033330    POINT (668152.1082198943 7230326.594352566)              79              0                   False        Coffea_bertrandii             214.0             214.0  ...         6765.0        10.0         9.0         7.0         5.0           20.0                 169.0                  295.0                   42.0          bertrandii
29         4326  46.674722 -25.122222    POINT (668843.6342847437 7220470.852634992)              79              0                   False        Coffea_bertrandii             219.0             219.0  ...         6517.0        10.0        15.0         7.0         5.0           88.0                 172.0                  293.0                   41.0          bertrandii
30         4326  46.683330 -25.066670      POINT (669788.333901034 7226613.03440059)              79              0                   False        Coffea_bertrandii             219.0             219.0  ...         7562.0        10.0        10.0         7.0         5.0           29.0                 173.0                  295.0                   43.0          bertrandii
31         4326  46.683333 -25.066667     POINT (669788.640688142 7226613.362913565)              79              0                   False        Coffea_bertrandii             219.0             219.0  ...         7562.0        10.0        10.0         7.0         5.0           29.0                 173.0                  295.0                   43.0          bertrandii
32         4326  46.758330 -25.150000     POINT (677234.4440133531 7217286.77883262)              79              0                   False        Coffea_bertrandii             219.5             219.0  ...         7298.0         1.0        21.0         4.0         5.0            3.0                 175.0                  283.0                   48.0          bertrandii
33         4326  47.866667 -21.383333     POINT (797253.6520891015 7632714.03380194)              79              0                   False        Coffea_bertrandii             216.0             215.0  ...         7706.0        10.0        11.0        16.0         3.0            0.0                 178.0                  276.0                   71.0          bertrandii
34         4326  44.732222 -16.931667   POINT (471486.44712923677 8127984.871431336)              79              0                   False          Coffea_dubardii             228.0             229.0  ...         7811.0         9.0        18.0         5.0         8.0           49.0                 204.0                  333.0                   23.0            dubardii
35         4326  44.749166 -16.958611  POINT (473294.49236259685 8125006.5619353615)              79              0                   False          Coffea_dubardii             221.5             222.0  ...         7620.0         9.0        18.0         5.0         8.0           71.0                 198.0                  328.0                   25.0            dubardii
36         4326  44.749167 -16.958611   POINT (473294.59883002134 8125006.562071315)              79              0                   False          Coffea_dubardii             221.5             222.0  ...         7620.0         9.0        18.0         5.0         8.0           71.0                 198.0                  328.0                   25.0            dubardii
37         4326  47.233333 -15.066667    POINT (740078.3644282935 8333083.596531117)              79              0                   False          Coffea_dubardii             231.0             230.0  ...         7632.0         5.0        20.0         5.0         9.0           62.0                 208.0                  339.0                   22.0            dubardii
38         4326  47.266667 -15.016667    POINT (743720.1593233433 8338580.996401502)              79              0                   False          Coffea_dubardii             233.0             232.0  ...         7768.0         5.0        20.0         3.0         9.0           72.0                 211.0                  340.0                   23.0            dubardii
39         4326  47.863889 -21.382500   POINT (796967.0982798996 7632811.5735395495)              79              0                   False          Coffea_dubardii             211.0             210.0  ...         7777.0        10.0        11.0        16.0         3.0            0.0                 173.0                  273.0                   69.0            dubardii
40         4326  47.863972 -21.382389    POINT (796975.9344399704 7632823.713043112)              79              0                   False          Coffea_dubardii             211.0             210.0  ...         7777.0        10.0        11.0        16.0         3.0            0.0                 173.0                  273.0                   69.0            dubardii
41         4326  47.867500 -21.375833    POINT (797355.2531098193 7633543.307278467)              79              0                   False          Coffea_dubardii             214.0             213.0  ...         6717.0        10.0        11.0        16.0         3.0           16.0                 176.0                  275.0                   70.0            dubardii
42         4326  49.055556 -12.922222    POINT (940259.7556518493 8567976.697977759)              79              0                   False          Coffea_dubardii             232.5             233.0  ...         7830.0         7.0        22.0         7.0        13.0           17.0                 215.0                  322.0                   30.0            dubardii
43         4326  49.066667 -12.850000    POINT (941594.6956003106 8575962.476910887)              79              0                   False          Coffea_dubardii             230.0             230.0  ...         7763.0         9.0         8.0         7.0        12.0           17.0                 212.0                  316.0                   28.0            dubardii
44         4326  49.072222 -12.932500    POINT (942053.5831398848 8566808.703762723)              79              0                   False          Coffea_dubardii             226.5             227.0  ...         7603.0         7.0        22.0         2.0        13.0           10.0                 208.0                  317.0                   29.0            dubardii
45         4326  49.083330 -12.500000    POINT (944014.5765139057 8614727.573604858)              79              0                   False          Coffea_dubardii             211.5             212.0  ...         8040.0         9.0        18.0         7.0        12.0            0.0                 190.0                  288.0                   19.0            dubardii
46         4326  49.083333 -12.900000    POINT (943319.0546159232 8570391.744125314)              79              0                   False          Coffea_dubardii             226.5             227.0  ...         7892.0         7.0        22.0         5.0        13.0           12.0                 208.0                  316.0                   29.0            dubardii
47         4326  49.100000 -12.900000    POINT (945131.3540197855 8570362.800563525)              79              0                   False          Coffea_dubardii             225.5             226.0  ...         7785.0         7.0        22.0         2.0        13.0            8.0                 207.0                  315.0                   28.0            dubardii
48         4326  49.105000 -12.846388    POINT (945770.0611607116 8576296.608845381)              79              0                   False          Coffea_dubardii             225.5             226.0  ...         7872.0         9.0         8.0         7.0        12.0           13.0                 207.0                  313.0                   27.0            dubardii
49         4326  49.105000 -12.846390    POINT (945770.0576231861 8576296.387159621)              79              0                   False          Coffea_dubardii             225.5             226.0  ...         7872.0         9.0         8.0         7.0        12.0           13.0                 207.0                  313.0                   27.0            dubardii
50         4326  49.105000 -12.846400     POINT (945770.0399355507 8576295.27873082)              79              0                   False          Coffea_dubardii             225.5             226.0  ...         7872.0         9.0         8.0         7.0        12.0           13.0                 207.0                  313.0                   27.0            dubardii
51         4326  49.106660 -12.916380    POINT (945826.4226579209 8568535.587778185)              79              0                   False          Coffea_dubardii             227.5             228.0  ...         7900.0         7.0        22.0         5.0        13.0           56.0                 209.0                  317.0                   29.0            dubardii

In [32]:
coffee_data_bin['extracted_specimen'] = coffee_data_bin['specimen_name'].str.split('_').str[1]
print(coffee_data_bin.head)

<bound method NDFrame.head of             specimen_id  source_crs  longitude   latitude                              mada_geom_point  sampled_layers  nodata_layers  is_categorical_encoded         specimen_name  clim_1_tmin1_jan  ...  env_78_wat_18  env_78_wat_15  env_78_wat_19  env_78_wat_24  env_78_wat_21  env_78_wat_0  clim_1_tmin1_jan_old  clim_13_tmax1_jan_old  clim_25_prec1_jan_old  extracted_specimen
0           abbayesii_0        4326  46.450000 -24.366660  POINT (647070.6204618097 7304410.220689219)              79              0                    True      Coffea_abbayesii             195.5  ...              0              0              0              0              0             0                 159.0                  307.0                   30.0           abbayesii
1           abbayesii_1        4326  46.830000 -24.730000  POINT (685086.8720605411 7263711.610572983)              79              0                    True      Coffea_abbayesii             177.5  ...              0              0              0              0              0             0                 139.0                  260.0                   52.0           abbayesii
2           abbayesii_2        4326  46.833300 -24.733300   POINT (685415.815086571 7263341.630764661)              79              0                    True      Coffea_abbayesii             177.5  ...              0              0              0              0              0             0                 139.0                  260.0                   52.0           abbayesii
3           abbayesii_3        4326  46.833330 -24.666670  POINT (685517.5605412831 7270721.614432366)              79              0                    True      Coffea_abbayesii             208.5  ...              0              0              0              0              0             0                 168.0                  292.0                   61.0           abbayesii
4           abbayesii_4        4326  46.833333 -24.733333  POINT (685419.1044266553 7263337.930920706)              79              0                    True      Coffea_abbayesii             177.5  ...              0              0              0              0              0             0                 139.0                  260.0                   52.0           abbayesii
..                  ...         ...        ...        ...                                          ...             ...            ...                     ...                   ...               ...  ...            ...            ...            ...            ...            ...           ...                   ...                    ...                    ...                 ...
463  vatovavyensis_3729        4326  47.866667 -21.383333   POINT (797253.6520891015 7632714.03380194)              79              0                    True  Coffea_vatovavyensis             216.0  ...              0              0              0              0              0             0                 178.0                  276.0                   71.0       vatovavyensis
464  vatovavyensis_3730        4326  47.933333 -21.400000  POINT (804136.3625319668 7630739.814647073)              79              0                    True  Coffea_vatovavyensis             208.0  ...              0              0              0              0              0             0                 170.0                  267.0                   69.0       vatovavyensis
465       vianneyi_3732        4326  47.863972 -21.382389  POINT (796975.9344399704 7632823.713043112)              79              0                    True       Coffea_vianneyi             211.0  ...              0              0              0              0              0             0                 173.0                  273.0                   69.0            vianneyi
466       vianneyi_3733        4326  47.866667 -21.383333   POINT (797253.6520891015 7632714.03380194)              79              0                    True       Coffea_vianneyi             216.0  ...              0              0              0              0              0             0                 178.0                  276.0                   71.0            vianneyi
467       vianneyi_3734        4326  47.867861 -21.377889   POINT (797388.5523752098 7633314.85921484)              79              0                    True       Coffea_vianneyi             214.0  ...              0              0              0              0              0             0                 176.0                  275.0                   70.0            vianneyi

[468 rows x 171 columns]>

In [33]:
caffeine_content['extracted_species'] = caffeine_content['Species_name'].str.split('_').str[1]
print(caffeine_content)

               Species_name  caffeine_percent  caffeine_class extracted_species
0   C_andrambovatensis_A310             0.000               0  andrambovatensis
1          C_abbayesii_A601             0.000               0         abbayesii
2         C_arenesiana_A403             0.000               0        arenesiana
3           C_bertrandii_A5             0.000               0        bertrandii
4           C_dubardii_A969             0.000               0          dubardii
..                      ...               ...             ...               ...
21          C_vianneyi_A946             0.040               1          vianneyi
22   C_farafanganensis_A208             0.045               1   farafanganensis
23          C_homollei_A945             0.060               1          homollei
24    C_kianjavatensis_A602             0.700               1    kianjavatensis
25        C_lancifolia_A320             0.700               1        lancifolia

[26 rows x 4 columns]

In [14]:
merged_df = pd.merge(
    coffee_data,
    caffeine_content[['extracted_species', 'Species_name', 'caffeine_percent','caffeine_class']],
    left_on='extracted_specimen',
    right_on='extracted_species',
    how='left'  # Use 'left' join to keep all rows from coffee_env_data
)

# Step 4: Drop the helper columns
merged_df = merged_df.drop(columns=['extracted_specimen', 'extracted_species'])

# The result is the original DataFrame with an additional 'caffeine_class' column
merged_df.to_csv(r'../data/coll_caff_node_w_class.csv', index=False)

In [ ]:
merged_df

In [34]:
merged_df_bin = pd.merge(
    coffee_data_bin,
    caffeine_content[['extracted_species', 'Species_name', 'caffeine_percent','caffeine_class']],
    left_on='extracted_specimen',
    right_on='extracted_species',
    how='left'  # Use 'left' join to keep all rows from coffee_env_data
)

# Step 4: Drop the helper columns
merged_df_bin = merged_df_bin.drop(columns=['extracted_specimen', 'extracted_species'])

# The result is the original DataFrame with an additional 'caffeine_class' column
merged_df_bin.to_csv(r'../data/coll_caff_node_bin_w_class.csv', index=False)

In [17]:
input_df = merged_df[["Species_name","longitude","latitude","caffeine_percent"]]
input_df = input_df.rename(columns={'Species_name': 'specimen_id'})
input_df.to_csv("../data/coords_w_caff.csv", index=False)
input_df

                 specimen_id  longitude   latitude  caffeine_percent
0           C_abbayesii_A601  46.450000 -24.366660             0.000
1           C_abbayesii_A601  46.830000 -24.730000             0.000
2           C_abbayesii_A601  46.833300 -24.733300             0.000
3           C_abbayesii_A601  46.833330 -24.666670             0.000
4           C_abbayesii_A601  46.833333 -24.733333             0.000
5           C_abbayesii_A601  46.850000 -24.800000             0.000
6           C_abbayesii_A601  46.863333 -24.760833             0.000
7           C_abbayesii_A601  46.962222 -24.836667             0.000
8           C_abbayesii_A601  47.136111 -24.842778             0.000
9           C_abbayesii_A601  47.136667 -24.835833             0.000
10          C_abbayesii_A601  47.140100 -24.835216             0.000
11          C_abbayesii_A601  47.166111 -24.796389             0.000
12          C_abbayesii_A601  47.863889 -21.382500             0.000
13          C_abbayesii_A601  47.866667 -21.383333             0.000
14          C_abbayesii_A601  47.867861 -21.377889             0.000
15   C_andrambovatensis_A310  47.750000 -21.516667             0.000
16   C_andrambovatensis_A310  47.758333 -21.525000             0.000
17   C_andrambovatensis_A310  47.866667 -21.383333             0.000
18         C_arenesiana_A403  47.533100 -18.939287             0.000
19         C_arenesiana_A403  47.928889 -18.919722             0.000
20         C_arenesiana_A403  48.033333 -18.883333             0.000
21         C_arenesiana_A403  48.216667 -19.177222             0.000
22         C_arenesiana_A403  48.228611 -19.177222             0.000
23         C_arenesiana_A403  48.254139 -19.120401             0.000
24         C_arenesiana_A403  48.275000 -18.950000             0.000
25           C_bertrandii_A5  46.486576 -24.820319             0.000
26           C_bertrandii_A5  46.633330 -25.016660             0.000
27           C_bertrandii_A5  46.639722 -25.023333             0.000
28           C_bertrandii_A5  46.666660 -25.033330             0.000
29           C_bertrandii_A5  46.674722 -25.122222             0.000
30           C_bertrandii_A5  46.683330 -25.066670             0.000
31           C_bertrandii_A5  46.683333 -25.066667             0.000
32           C_bertrandii_A5  46.758330 -25.150000             0.000
33           C_bertrandii_A5  47.866667 -21.383333             0.000
34           C_dubardii_A969  44.732222 -16.931667             0.000
35           C_dubardii_A969  44.749166 -16.958611             0.000
36           C_dubardii_A969  44.749167 -16.958611             0.000
37           C_dubardii_A969  47.233333 -15.066667             0.000
38           C_dubardii_A969  47.266667 -15.016667             0.000
39           C_dubardii_A969  47.863889 -21.382500             0.000
40           C_dubardii_A969  47.863972 -21.382389             0.000
41           C_dubardii_A969  47.867500 -21.375833             0.000
42           C_dubardii_A969  49.055556 -12.922222             0.000
43           C_dubardii_A969  49.066667 -12.850000             0.000
44           C_dubardii_A969  49.072222 -12.932500             0.000
45           C_dubardii_A969  49.083330 -12.500000             0.000
46           C_dubardii_A969  49.083333 -12.900000             0.000
47           C_dubardii_A969  49.100000 -12.900000             0.000
48           C_dubardii_A969  49.105000 -12.846388             0.000
49           C_dubardii_A969  49.105000 -12.846390             0.000
50           C_dubardii_A969  49.105000 -12.846400             0.000
51           C_dubardii_A969  49.106660 -12.916380             0.000
52           C_dubardii_A969  49.106667 -12.916389             0.000
53           C_dubardii_A969  49.106670 -12.916390             0.000
54           C_dubardii_A969  49.106944 -12.910000             0.000
55           C_dubardii_A969  49.109720 -12.908880             0.000
56           C_dubardii_A969  49.111670 -12.911670             0.000
57           C_dubardii_A969  49.116667 -12.933333             0.000
58           C_dubardii_A969  49.116670 -12.933330             0.000
59           C_dubardii_A969  49.130000 -12.570000             0.000
60           C_dubardii_A969  49.133333 -12.566667             0.000
61           C_dubardii_A969  49.133333 -12.750000             0.000
62           C_dubardii_A969  49.166670 -12.950000             0.000
63           C_dubardii_A969  49.172500 -12.487778             0.000
64           C_dubardii_A969  49.172500 -12.487780             0.000
65           C_dubardii_A969  49.174722 -12.482778             0.000
66           C_dubardii_A969  49.213056 -12.479722             0.000
67           C_dubardii_A969  49.218333 -12.578889             0.000
68           C_dubardii_A969  49.233330 -12.866660             0.000
69           C_dubardii_A969  49.256111 -12.459167             0.000
70           C_dubardii_A969  49.258333 -12.825000             0.000
71           C_dubardii_A969  49.333330 -12.383330             0.000
72           C_dubardii_A969  49.700000 -13.180000             0.000
73           C_dubardii_A969  49.766667 -13.200000             0.000
74           C_dubardii_A969  49.985833 -13.613056             0.000
75    C_farafanganensis_A208  47.641667 -23.141667             0.045
76    C_farafanganensis_A208  47.700000 -23.000000             0.045
77    C_farafanganensis_A208  47.863889 -21.382500             0.045
78    C_farafanganensis_A208  47.863972 -21.382389             0.045
79    C_farafanganensis_A208  47.866667 -21.383333             0.045
80             C_heimii_A516  46.706110 -19.373330             0.000
81             C_heimii_A516  47.863889 -21.382500             0.000
82             C_heimii_A516  47.866667 -21.383333             0.000
83             C_heimii_A516  49.202966 -12.221671             0.000
84             C_heimii_A516  49.226443 -12.281807             0.000
85             C_heimii_A516  49.263119 -12.279828             0.000
86             C_heimii_A516  49.275700 -12.398991             0.000
87             C_heimii_A516  49.303872 -12.318289             0.000
88             C_heimii_A516  49.306528 -12.355424             0.000
89             C_heimii_A516  49.319958 -12.231176             0.000
90             C_heimii_A516  49.342500 -12.396327             0.000
91             C_heimii_A516  49.347115 -12.210881             0.000
92             C_heimii_A516  49.353050 -12.373610             0.000
93             C_heimii_A516  49.387585 -12.322474             0.000
94             C_heimii_A516  49.398762 -12.388760             0.000
95             C_heimii_A516  49.433330 -12.566660             0.000
96             C_heimii_A516  49.433333 -12.566667             0.000
97             C_heimii_A516  49.435269 -12.278797             0.000
98             C_heimii_A516  49.442777 -12.593611             0.000
99             C_heimii_A516  49.456110 -12.584720             0.000
100            C_heimii_A516  49.549809 -12.580463             0.000
101            C_heimii_A516  49.569592 -12.454103             0.000
102            C_heimii_A516  49.583333 -12.970278             0.000
103          C_homollei_A945  47.863889 -21.382500             0.060
104          C_homollei_A945  47.866667 -21.383333             0.060
105          C_homollei_A945  48.581389 -19.163056             0.060
106          C_homollei_A945  48.731110 -17.503880             0.060
107          C_homollei_A945  48.731111 -17.503889             0.060
108          C_homollei_A945  49.200000 -17.916667             0.060
109          C_homollei_A945  49.203333 -17.931667             0.060
110          C_homollei_A945  49.266940 -16.862500             0.060
111          C_homollei_A945  49.266944 -16.862500             0.060
112       C_humbertii_RNF785  43.610638 -23.078725             0.000
113       C_humbertii_RNF785  43.625805 -23.250722             0.000
114       C_humbertii_RNF785  43.625806 -23.250722             0.000
115       C_humbertii_RNF785  43.665555 -23.066388             0.000
116       C_humbertii_RNF785  43.714444 -23.002222             0.000
117       C_humbertii_RNF785  43.784722 -23.451389             0.000
118       C_humbertii_RNF785  43.797500 -22.875000             0.000
119       C_humbertii_RNF785  43.916667 -23.200000             0.000
120       C_humbertii_RNF785  43.983330 -23.266670             0.000
121       C_humbertii_RNF785  43.983333 -23.266667             0.000
122       C_humbertii_RNF785  43.983334 -23.266667             0.000
123       C_humbertii_RNF785  44.033333 -23.216667             0.000
124       C_humbertii_RNF785  44.052500 -23.188611             0.000
125       C_humbertii_RNF785  44.052778 -23.186389             0.000
126       C_humbertii_RNF785  44.100000 -23.133333             0.000
127       C_humbertii_RNF785  44.136600 -23.531800             0.000
128       C_humbertii_RNF785  44.155000 -23.526389             0.000
129       C_humbertii_RNF785  44.283330 -23.883330             0.000
130       C_humbertii_RNF785  44.283333 -23.883333             0.000
131       C_humbertii_RNF785  44.283333 -23.883334             0.000
132       C_humbertii_RNF785  44.350000 -23.733333             0.000
133       C_humbertii_RNF785  44.383333 -23.733333             0.000
134       C_humbertii_RNF785  44.400000 -23.833333             0.000
135       C_humbertii_RNF785  44.580000 -22.920000             0.000
136       C_humbertii_RNF785  44.583333 -22.916667             0.000
137       C_humbertii_RNF785  44.632515 -23.650485             0.000
138       C_humbertii_RNF785  44.633330 -23.666660             0.000
139       C_humbertii_RNF785  44.633333 -23.666667             0.000
140       C_humbertii_RNF785  44.650000 -23.666660             0.000
141       C_humbertii_RNF785  44.680000 -22.830000             0.000
142       C_humbertii_RNF785  44.680000 -22.880000             0.000
143       C_humbertii_RNF785  44.681028 -22.878083             0.000
144       C_humbertii_RNF785  44.683333 -22.783333             0.000
145       C_humbertii_RNF785  44.690055 -22.888583             0.000
146       C_humbertii_RNF785  44.700000 -22.700000             0.000
147       C_humbertii_RNF785  45.100000 -20.166667             0.000
148       C_humbertii_RNF785  45.116667 -20.183333             0.000
149    C_humblotiana_BM19_20  43.650000 -12.300000             0.000
150    C_humblotiana_BM19_20  45.027580 -12.911156             0.000
151    C_humblotiana_BM19_20  45.066670 -12.716670             0.000
152    C_humblotiana_BM19_20  45.076510 -12.715370             0.000
153    C_humblotiana_BM19_20  45.095965 -12.869054             0.000
154    C_humblotiana_BM19_20  45.140836 -12.684678             0.000
155    C_humblotiana_BM19_20  45.141280 -12.959820             0.000
156    C_humblotiana_BM19_20  45.147430 -12.820600             0.000
157    C_humblotiana_BM19_20  45.157940 -12.875560             0.000
158    C_humblotiana_BM19_20  45.166260 -12.871020             0.000
159    C_humblotiana_BM19_20  45.172790 -12.764470             0.000
160    C_humblotiana_BM19_20  45.183400 -12.765320             0.000
161    C_humblotiana_BM19_20  47.863889 -21.382500             0.000
162    C_humblotiana_BM19_20  47.866667 -21.383333             0.000
163    C_kianjavatensis_A602  47.850000 -21.383333             0.700
164    C_kianjavatensis_A602  47.858610 -21.380280             0.700
165    C_kianjavatensis_A602  47.866667 -21.383333             0.700
166    C_kianjavatensis_A602  47.939444 -21.388333             0.700
167        C_lancifolia_A320  47.866667 -21.383333             0.700
168        C_lancifolia_A320  49.203333 -17.931666             0.700
169        C_lancifolia_A320  49.203333 -17.931667             0.700
170            C_leroyi_A315  44.016670 -23.250000             0.020
171            C_leroyi_A315  47.650000 -21.283333             0.020
172            C_leroyi_A315  47.866660 -21.383330             0.020
173            C_leroyi_A315  47.866667 -21.383333             0.020
174            C_leroyi_A315  47.867778 -21.375000             0.020
175            C_leroyi_A315  48.722220 -17.542220             0.020
176            C_leroyi_A315  48.746667 -17.484167             0.020
177            C_leroyi_A315  48.767770 -17.506940             0.020
178            C_leroyi_A315  49.285830 -14.336660             0.020
179            C_leroyi_A315  49.301389 -14.325556             0.020
180            C_leroyi_A315  49.311110 -14.301660             0.020
181            C_leroyi_A315  49.403330 -14.611110             0.020
182            C_leroyi_A315  49.688880 -14.587770             0.020
183            C_leroyi_A315  49.688890 -14.587780             0.020
184          C_millotii_A222  47.000000 -23.000000             0.000
185          C_millotii_A222  47.863889 -21.382500             0.000
186          C_millotii_A222  47.866667 -21.383333             0.000
187          C_millotii_A222  47.867222 -21.376389             0.000
188          C_millotii_A222  47.867500 -21.375833             0.000
189          C_millotii_A222  47.868333 -21.375278             0.000
190          C_millotii_A222  47.870278 -21.376944             0.000
191          C_millotii_A222  47.941111 -21.402778             0.000
192          C_millotii_A222  47.942500 -21.406944             0.000
193          C_millotii_A222  48.292499 -18.866111             0.000
194          C_millotii_A222  48.292500 -18.866110             0.000
195          C_millotii_A222  48.318880 -18.869440             0.000
196          C_millotii_A222  48.318888 -18.869444             0.000
197          C_millotii_A222  48.556111 -19.158611             0.000
198          C_millotii_A222  48.883330 -17.533330             0.000
199          C_millotii_A222  48.893060 -17.533330             0.000
200          C_millotii_A222  49.198056 -18.036111             0.000
201          C_millotii_A222  49.203330 -17.931670             0.000
202          C_millotii_A222  49.203333 -17.931667             0.000
203          C_millotii_A222  49.450000 -14.700000             0.000
204          C_millotii_A222  49.454450 -17.704817             0.000
205          C_millotii_A222  49.550833 -13.218889             0.000
206          C_millotii_A222  49.733333 -15.433333             0.000
207          C_millotii_A222  49.750000 -15.483330             0.000
208          C_millotii_A222  49.766660 -15.500000             0.000
209          C_millotii_A222  49.766667 -15.500000             0.000
210          C_millotii_A222  49.769400 -15.494400             0.000
211          C_millotii_A222  49.786667 -16.452500             0.000
212          C_millotii_A222  49.790400 -16.474388             0.000
213          C_millotii_A222  49.861111 -14.401111             0.000
214          C_millotii_A222  49.866660 -15.416660             0.000
215          C_millotii_A222  49.950000 -15.066667             0.000
216          C_millotii_A222  49.966660 -15.616660             0.000
217          C_millotii_A222  49.966660 -15.683330             0.000
218          C_millotii_A222  49.981940 -15.620830             0.000
219          C_millotii_A222  50.206940 -15.805550             0.000
220          C_millotii_A222  50.225000 -15.692500             0.000
221          C_millotii_A222  50.250000 -15.683330             0.000
222           C_perrieri_A12  44.050504 -18.043941             0.000
223           C_perrieri_A12  44.145556 -22.707778             0.000
224           C_perrieri_A12  44.156111 -22.718056             0.000
225           C_perrieri_A12  44.263056 -22.845833             0.000
226           C_perrieri_A12  44.272222 -22.853611             0.000
227           C_perrieri_A12  44.287778 -22.820556             0.000
228           C_perrieri_A12  44.288056 -22.820833             0.000
229           C_perrieri_A12  44.324103 -18.035903             0.000
230           C_perrieri_A12  44.472220 -17.939720             0.000
231           C_perrieri_A12  44.472222 -17.939722             0.000
232           C_perrieri_A12  44.516667 -18.027778             0.000
233           C_perrieri_A12  44.561940 -18.111390             0.000
234           C_perrieri_A12  44.561944 -18.111388             0.000
235           C_perrieri_A12  44.561944 -18.111389             0.000
236           C_perrieri_A12  44.791667 -19.141667             0.000
237           C_perrieri_A12  45.116667 -16.216667             0.000
238           C_perrieri_A12  45.365556 -21.188611             0.000
239           C_perrieri_A12  45.375278 -22.153056             0.000
240           C_perrieri_A12  45.375278 -22.486389             0.000
241           C_perrieri_A12  45.985053 -17.067958             0.000
242           C_perrieri_A12  45.989000 -17.062690             0.000
243           C_perrieri_A12  45.989986 -17.052635             0.000
244           C_perrieri_A12  45.993359 -17.044592             0.000
245           C_perrieri_A12  46.015693 -17.117573             0.000
246           C_perrieri_A12  46.015711 -17.117819             0.000
247           C_perrieri_A12  46.109722 -24.310833             0.000
248           C_perrieri_A12  46.145833 -24.303611             0.000
249           C_perrieri_A12  46.157770 -24.336380             0.000
250           C_perrieri_A12  46.333889 -24.560833             0.000
251           C_perrieri_A12  46.473056 -25.023333             0.000
252           C_perrieri_A12  46.599722 -24.793889             0.000
253           C_perrieri_A12  46.600000 -24.800000             0.000
254           C_perrieri_A12  46.602230 -24.803730             0.000
255           C_perrieri_A12  46.603611 -24.806111             0.000
256           C_perrieri_A12  46.611944 -24.806111             0.000
257           C_perrieri_A12  46.639722 -25.023333             0.000
258           C_perrieri_A12  46.673333 -24.798889             0.000
259           C_perrieri_A12  46.783333 -22.316667             0.000
260           C_perrieri_A12  47.019730 -16.763061             0.000
261           C_perrieri_A12  47.781762 -14.795310             0.000
262           C_perrieri_A12  47.863889 -21.382500             0.000
263           C_perrieri_A12  47.867222 -21.376389             0.000
264           C_perrieri_A12  49.766670 -14.283330             0.000
265       C_pervilleana_A957  44.284170 -17.543610             0.000
266       C_pervilleana_A957  44.284300 -17.543506             0.000
267       C_pervilleana_A957  44.301390 -18.015280             0.000
268       C_pervilleana_A957  44.301506 -18.015404             0.000
269       C_pervilleana_A957  44.315803 -18.033509             0.000
270       C_pervilleana_A957  44.315830 -18.033610             0.000
271       C_pervilleana_A957  44.324308 -18.035903             0.000
272       C_pervilleana_A957  44.433333 -18.941667             0.000
273       C_pervilleana_A957  44.497196 -18.032096             0.000
274       C_pervilleana_A957  44.516667 -18.061111             0.000
275       C_pervilleana_A957  44.561388 -18.117777             0.000
276       C_pervilleana_A957  44.561389 -18.117778             0.000
277       C_pervilleana_A957  44.561390 -18.117780             0.000
278       C_pervilleana_A957  44.775000 -18.683333             0.000
279       C_pervilleana_A957  45.350000 -16.433333             0.000
280       C_pervilleana_A957  45.920397 -17.077081             0.000
281       C_pervilleana_A957  45.923007 -17.078820             0.000
282       C_pervilleana_A957  46.706040 -19.373383             0.000
283       C_pervilleana_A957  46.816667 -16.300000             0.000
284       C_pervilleana_A957  47.866667 -21.383333             0.000
285       C_pervilleana_A957  47.867500 -21.376389             0.000
286       C_pervilleana_A957  48.250000 -13.333330             0.000
287       C_pervilleana_A957  48.300000 -13.416660             0.000